import { generateProductCode } from "@/lib/kasir-catalog";
import type { Product } from "@/types/product";

const BRG_PATTERN = /^BRG-(\d+)$/i;
const PRD_ID_PATTERN = /^PRD-(\d+)$/i;

/** Kode BRG tersimpan di field serialNumber untuk barang tanpa serial pabrik */
export function isAutoGeneratedBrgCode(value: string | undefined): boolean {
  if (!value?.trim()) return false;
  return BRG_PATTERN.test(value.trim());
}

export function getNextBrgSequence(products: Product[]): number {
  let max = 0;
  for (const p of products) {
    const sn = p.serialNumber?.trim();
    if (!sn) continue;
    const match = BRG_PATTERN.exec(sn);
    if (match) max = Math.max(max, Number.parseInt(match[1], 10));
  }
  return max + 1;
}

export function createNextBrgCode(products: Product[]): string {
  return generateProductCode(getNextBrgSequence(products));
}

export function createNextProductId(products: Product[]): string {
  let max = 0;
  for (const p of products) {
    const match = PRD_ID_PATTERN.exec(p.id);
    if (match) max = Math.max(max, Number.parseInt(match[1], 10));
  }
  return `PRD-${String(max + 1).padStart(3, "0")}`;
}

export function resolveSerialOrCode(
  products: Product[],
  hasSerialNumber: boolean,
  manualSerial: string,
  editingId?: string | null,
): string | undefined {
  if (hasSerialNumber) {
    const trimmed = manualSerial.trim();
    return trimmed || undefined;
  }

  if (editingId) {
    const existing = products.find((p) => p.id === editingId);
    const existingSn = existing?.serialNumber?.trim();
    if (existingSn && isAutoGeneratedBrgCode(existingSn)) {
      return existingSn;
    }
  }

  return createNextBrgCode(products);
}

/** Saat edit: centang jika punya serial pabrik (bukan kode BRG otomatis) */
export function inferHasFactorySerial(product: Product): boolean {
  const sn = product.serialNumber?.trim();
  if (!sn) return false;
  return !isAutoGeneratedBrgCode(sn);
}

export function formatCodeOrSerial(product: Product): string {
  return product.serialNumber?.trim() || "—";
}
